addSbtPlugin("com.lightbend.lagom" % "lagom-sbt-plugin" % "1.0.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-bintray-bundle" % "1.0.2")
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "3.0.0")
addSbtPlugin("com.github.ddispaltro" % "sbt-reactjs" % "0.5.2")
addSbtPlugin("com.lightbend.conductr" % "sbt-conductr" % "2.1.4")
